# Generated by Django 3.2.9 on 2021-11-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='user',
        ),
    ]
